"""
Django settings for coffeehouse project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# Snippet taken from Code Institute material
import os
import dj_database_url
if os.path.isfile('env.py'):
    import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=g_pbb8b-3x0&$j^qk3#avh8nq1aq$d2o7=6pj7vqb-at8$7ni'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['.herokuapp.com',
                 '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'members',
    'coffeetables',
    "cloudinary",
    "cloudinary_storage",
    # Below 4 entries taken from Code Institute material
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Snippet taken from W3Dschools https://www.w3schools.com/django/django_static_whitenoise.php
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Snippet taken from Code Institute material
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'coffeehouse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coffeehouse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Snippet taken from Code Institute material
DATABASES = {
    'default': dj_database_url.parse(os.environ.get("DATABASE_URL"))
}

AUTH_USER_MODEL = "members.CoffeeDrinker"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# snippet taken from W3Dschools https://www.w3schools.com/django/django_collect_static_files.php
STATIC_ROOT = BASE_DIR / 'productionfiles'

# snippet taken from W3Dschools https://www.w3schools.com/django/django_add_global_static_files.php
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

#Cloudinary settings set up using ChatGPT
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media locations referenced following Codemy tutorial
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Allauth fields 
# Fields are taken from Code Institute material and ChatGPT

SITE_ID = 1
LOGIN_REDIRECT_URL = 'tables'
ACCOUNT_LOGOUT_REDIRECT_URL = "account_login"

ACCOUNT_LOGIN_METHODS = {"username", "email"}   # username/email login
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "none"       # or "mandatory" if you set up SMTP
ACCOUNT_LOGOUT_ON_GET = True              # optional convenience
ACCOUNT_SESSION_REMEMBER = True

ACCOUNT_FORMS = {
    "signup": "members.forms.AllauthSignupForm",
    "login": "members.forms.AllauthLoginForm",
    "reset_password": "members.forms.AllauthResetPasswordForm",
    "reset_password_from_key": "members.forms.AllauthChangePasswordForm",
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# SMTP fields generated using ChatGPT
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("env_email_host")
EMAIL_HOST_PASSWORD = os.environ.get("env_email_password")
DEFAULT_FROM_EMAIL = os.environ.get("env_email_default")

ACCOUNT_EMAIL_SUBJECT_PREFIX = "Coffeehouse "
